"use client";
import {useEffect,useMemo,useState} from "react";

type Tab="Dashboard"|"Watchlist"|"Screener"|"Crypto"|"Token Lab"|"News"|"AI"|"Portfolio"|"Alerts";
type Quote={symbol:string;name:string;price:number|null;change:number|null;currency:string;marketState:string};
type Chat={role:"user"|"assistant";content:string};
const DEFAULTS=["NVDA","TSLA","AMD","AAPL","MSFT","SPY","QQQ","COIN"];
const fmt=(n:number|null|undefined,d=2)=>n==null||Number.isNaN(n)?"—":`$${n.toLocaleString(undefined,{minimumFractionDigits:d,maximumFractionDigits:d})}`;
const pct=(n:number|null|undefined)=>n==null?"—":`${n>=0?"+":""}${n.toFixed(2)}%`;
const num=(x:any)=>typeof x==="number"?x:Number(x||0);

export default function Home(){
 const [tab,setTab]=useState<Tab>("Dashboard"),[watch,setWatch]=useState(DEFAULTS),[quotes,setQuotes]=useState<Quote[]>([]),[search,setSearch]=useState(""),[chat,setChat]=useState<Chat[]>([]),[q,setQ]=useState(""),[busy,setBusy]=useState(false),[updated,setUpdated]=useState<Date|null>(null);
 const [cryptoPairs,setCrypto]=useState<any[]>([]),[news,setNews]=useState<any[]>([]),[token,setToken]=useState<any>(null),[tokenAddress,setTokenAddress]=useState(""),[wallet,setWallet]=useState<any>(null),[walletAddress,setWalletAddress]=useState("");
 const [paperCash,setPaperCash]=useState(10000),[paperPos,setPaperPos]=useState<Record<string,number>>({}),[paperSymbol,setPaperSymbol]=useState("NVDA"),[paperQty,setPaperQty]=useState(1);
 const [alerts,setAlerts]=useState<any[]>([]),[alertSymbol,setAlertSymbol]=useState("NVDA"),[alertPrice,setAlertPrice]=useState(""),[alertDir,setAlertDir]=useState("above"),[health,setHealth]=useState<any>(null);
 const [chart,setChart]=useState<any[]>([]),[chartSymbol,setChartSymbol]=useState("NVDA");
 useEffect(()=>{try{const w=localStorage.getItem("rogue-watchlist");if(w)setWatch(JSON.parse(w));const p=localStorage.getItem("rogue-paper");if(p){const x=JSON.parse(p);setPaperCash(x.cash??10000);setPaperPos(x.pos??{})}const a=localStorage.getItem("rogue-alerts");if(a)setAlerts(JSON.parse(a))}catch{}},[]);
 useEffect(()=>localStorage.setItem("rogue-watchlist",JSON.stringify(watch)),[watch]);
 useEffect(()=>localStorage.setItem("rogue-paper",JSON.stringify({cash:paperCash,pos:paperPos})),[paperCash,paperPos]);
 useEffect(()=>localStorage.setItem("rogue-alerts",JSON.stringify(alerts)),[alerts]);
 async function loadQuotes(){try{const r=await fetch(`/api/market?symbols=${encodeURIComponent(watch.join(","))}`,{cache:"no-store"});const j=await r.json();setQuotes(j.results||[]);setUpdated(new Date())}catch{}}
 async function loadCrypto(term="solana"){try{const r=await fetch(`/api/crypto?q=${encodeURIComponent(term)}`,{cache:"no-store"});setCrypto((await r.json()).pairs||[])}catch{}}
 async function loadNews(term="markets crypto AI"){try{const r=await fetch(`/api/news?q=${encodeURIComponent(term)}`,{cache:"no-store"});setNews((await r.json()).items||[])}catch{}}
 async function inspectToken(addr=tokenAddress){if(!addr.trim())return;try{const r=await fetch(`/api/token?address=${encodeURIComponent(addr.trim())}`,{cache:"no-store"});setToken(await r.json())}catch{setToken({error:"Token lookup failed"})}}
 async function inspectWallet(addr=walletAddress){if(!addr.trim())return;try{const r=await fetch(`/api/wallet?address=${encodeURIComponent(addr.trim())}`,{cache:"no-store"});setWallet(await r.json())}catch{setWallet({error:"Wallet lookup failed"})}}
 async function loadChart(s=chartSymbol){try{const r=await fetch(`/api/chart?symbol=${encodeURIComponent(s)}`,{cache:"no-store"});setChart((await r.json()).points||[])}catch{setChart([])}}
 useEffect(()=>{loadQuotes();const t=setInterval(loadQuotes,15000);return()=>clearInterval(t)},[watch.join(",")]);
 useEffect(()=>{fetch('/api/health',{cache:'no-store'}).then(r=>r.json()).then(setHealth).catch(()=>{})},[]);
 useEffect(()=>{if(tab==="Crypto")loadCrypto();if(tab==="News")loadNews();if(tab==="Portfolio")loadChart(paperSymbol);if(tab==="Dashboard")loadChart(chartSymbol)},[tab]);
 useEffect(()=>{if(tab==="Dashboard")loadChart(chartSymbol)},[chartSymbol]);
 useEffect(()=>{if(tab!=="Alerts")return;const timer=setInterval(()=>{for(const a of alerts){const p=quotes.find(x=>x.symbol===a.symbol)?.price;if(p==null)continue;const hit=a.dir==="above"?p>=a.price:p<=a.price;if(hit&&!a.fired){setAlerts(v=>v.map(x=>x.id===a.id?{...x,fired:true}:x));try{new Notification(`ROGUE alert: ${a.symbol}`,{body:`${a.symbol} crossed ${fmt(a.price)}`})}catch{}}}},5000);return()=>clearInterval(timer)},[tab,alerts,quotes]);
 function add(){const s=search.trim().toUpperCase();if(s&&!watch.includes(s))setWatch(v=>[...v,s].slice(0,40));setSearch("")}
 async function ask(text=q){const question=text.trim();if(!question||busy)return;setQ("");setTab("AI");setBusy(true);const next=[...chat,{role:"user",content:question} as Chat];setChat(next);try{const r=await fetch('/api/ai',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({messages:next,context:{watchlist:quotes.map(x=>({symbol:x.symbol,price:x.price,change:x.change})),crypto:cryptoPairs.slice(0,8).map(x=>({symbol:x.base?.symbol,price:x.priceUsd,liquidity:x.liquidity?.usd,change:x.priceChange?.h24})),token:token?.bestPair?{address:token.address,price:token.bestPair.priceUsd,liquidity:token.bestPair.liquidity?.usd,marketCap:token.bestPair.marketCap}:null,time:new Date().toISOString()}})});const j=await r.json();setChat(v=>[...v,{role:'assistant',content:j.answer||j.error||'No response.'}])}catch{setChat(v=>[...v,{role:'assistant',content:'ROGUE could not reach the AI service.'}])}finally{setBusy(false)}}
 function buy(){const qt=Math.max(0,Number(paperQty)||0),p=quotes.find(x=>x.symbol===paperSymbol)?.price;if(!p||qt<=0||paperCash<p*qt)return;setPaperCash(c=>c-p*qt);setPaperPos(v=>({...v,[paperSymbol]:(v[paperSymbol]||0)+qt}))}
 function sell(){const qt=Math.max(0,Number(paperQty)||0),p=quotes.find(x=>x.symbol===paperSymbol)?.price||0,h=paperPos[paperSymbol]||0,s=Math.min(qt,h);if(!p||!s)return;setPaperCash(c=>c+p*s);setPaperPos(v=>({...v,[paperSymbol]:h-s}))}
 const movers=useMemo(()=>[...quotes].sort((a,b)=>num(b.change)-num(a.change)),[quotes]);
 const portfolioValue=useMemo(()=>paperCash+Object.entries(paperPos).reduce((a,[s,n])=>a+n*(quotes.find(q=>q.symbol===s)?.price||0),0),[paperCash,paperPos,quotes]);
 const mint=process.env.NEXT_PUBLIC_ROGUE_MINT||"";const buyUrl=mint?`https://pump.fun/coin/${mint}`:"https://pump.fun/";
 return <main className="app"><aside><div className="logo"><span>R</span>OGUE</div><div className="tag">MARKETS // INTELLIGENCE TERMINAL</div><div className="live"><i/> LIVE SYSTEM</div><nav>{(["Dashboard","Watchlist","Screener","Crypto","Token Lab","News","AI","Portfolio","Alerts"] as Tab[]).map(x=><button className={tab===x?"active":""} onClick={()=>setTab(x)} key={x}>{x}</button>)}</nav><div className="sideStatus"><b>ROGUE AI</b><span>{health?.ai?"AI ONLINE":"API KEY REQUIRED"}</span><span>{health?.token?"$ROGUE LINKED":"TOKEN NOT LINKED"}</span></div><a href={buyUrl} target="_blank" rel="noreferrer" className="buy">BUY $ROGUE ↗</a></aside>
 <section className="main"><header><div><b>{tab.toUpperCase()}</b><span className="livePill"><i/> LIVE</span></div><div className="headActions">{updated?`Updated ${updated.toLocaleTimeString()}`:"Connecting…"}<button onClick={loadQuotes}>↻</button></div></header>
 {tab==="Dashboard"&&<Dashboard q={q} setQ={setQ} ask={ask} quotes={quotes} watch={watch} setWatch={setWatch} movers={movers} chart={chart} chartSymbol={chartSymbol} setChartSymbol={setChartSymbol} health={health} buyUrl={buyUrl}/>} 
 {tab==="Watchlist"&&<><PageHead title="Watchlist" text="Your live market radar. Add up to 40 symbols; data refreshes automatically."/><div className="add"><input value={search} onChange={e=>setSearch(e.target.value)} onKeyDown={e=>e.key==='Enter'&&add()} placeholder="Add AAPL, BTC-USD, COIN…"/><button onClick={add}>+ ADD</button></div><QuotePanel quotes={quotes} watch={watch} setWatch={setWatch}/></>}
 {tab==="Screener"&&<><PageHead title="Screener" text="Fast signal discovery across the symbols you are tracking."/><div className="cards2"><List title="TOP GAINERS" items={movers.filter(x=>num(x.change)>0).slice(0,10)}/><List title="TOP LOSERS" items={movers.filter(x=>num(x.change)<0).slice(-10).reverse()}/></div></>}
 {tab==="Crypto"&&<><PageHead title="Crypto Radar" text="Live Solana pair discovery, liquidity, volume and price movement."/><div className="add"><input value={search} onChange={e=>setSearch(e.target.value)} onKeyDown={e=>e.key==='Enter'&&loadCrypto(search||'solana')} placeholder="Search token, ticker or mint"/><button onClick={()=>loadCrypto(search||'solana')}>SEARCH</button></div><div className="cryptoGrid">{cryptoPairs.map((p:any,i)=><a className="crypto" href={p.url} target="_blank" rel="noreferrer" key={`${p.pairAddress}-${i}`}><div><b>${p.base?.symbol||'?'}</b><span>{p.base?.name||'Unknown'} · {p.dexId}</span></div><strong>{p.priceUsd?fmt(num(p.priceUsd),6):'—'}</strong><small>MC {p.marketCap?fmt(num(p.marketCap),0):'—'} · LIQ {p.liquidity?.usd?fmt(num(p.liquidity.usd),0):'—'} · VOL {p.volume?.h24?fmt(num(p.volume.h24),0):'—'}</small><em className={num(p.priceChange?.h24)>=0?'up':'down'}>{p.priceChange?.h24!=null?pct(num(p.priceChange.h24)):'—'}</em></a>)}</div></>}
 {tab==="Token Lab"&&<><PageHead title="Token Lab" text="Inspect a Solana token across market data, supply and liquidity. Always verify the mint address before trading."/><div className="add"><input value={tokenAddress} onChange={e=>setTokenAddress(e.target.value)} placeholder="Paste Solana token mint"/><button onClick={()=>inspectToken()}>INSPECT</button></div>{token&&<div className="cards2"><div className="panel"><Title t="TOKEN" s={token.address?.slice(0,6)+'…'+token.address?.slice(-6)}/><div className="big">{token.bestPair?.baseToken?.symbol||'TOKEN'}</div><div className="metricGrid"><Metric l="PRICE" v={token.bestPair?.priceUsd?fmt(num(token.bestPair.priceUsd),8):'—'}/><Metric l="MC" v={token.bestPair?.marketCap?fmt(num(token.bestPair.marketCap),0):'—'}/><Metric l="LIQUIDITY" v={token.bestPair?.liquidity?.usd?fmt(num(token.bestPair.liquidity.usd),0):'—'}/><Metric l="24H VOL" v={token.bestPair?.volume?.h24?fmt(num(token.bestPair.volume.h24),0):'—'}/></div></div><div className="panel"><Title t="RISK CHECKS" s="FACTS, NOT A SCORE"/><Signal t="Address" d="Compare the mint address against the official project source before buying."/><Signal t="Liquidity" d={token.bestPair?.liquidity?.usd?`Largest detected Solana pair has ${fmt(num(token.bestPair.liquidity.usd),0)} liquidity.`:'Liquidity unavailable.'}/><Signal t="Supply" d={token.supply?.uiAmountString?`Reported token supply: ${token.supply.uiAmountString}.`: 'Supply unavailable.'}/><Signal t="Venue" d={token.bestPair?.dexId?`Largest detected pair: ${token.bestPair.dexId}.`: 'No Solana pair found.'}/></div></div>}</>}
 {tab==="News"&&<><PageHead title="News" text="Fresh market headlines. Open the source and verify material claims before acting."/><div className="add"><input value={search} onChange={e=>setSearch(e.target.value)} placeholder="Search headlines"/><button onClick={()=>loadNews(search||'markets crypto AI')}>SEARCH</button></div><div className="news">{news.map((n:any,i)=><a href={n.link} target="_blank" rel="noreferrer" key={i}><b>{n.title}</b><span>{n.source||'News'} · {n.pubDate?new Date(n.pubDate).toLocaleString():''}</span></a>)}</div></>}
 {tab==="AI"&&<><PageHead title="ROGUE AI" text="A research copilot with live terminal context and web search. Ask it to explain, compare, calculate or investigate."/><div className="chat">{chat.length===0&&<div className="empty"><div>◈</div><h2>Ask ROGUE anything</h2><p>Try “Analyze my watchlist”, “Inspect this token”, “Explain the liquidity risk”, or “What changed today?”</p></div>}{chat.map((m,i)=><div className={m.role==='user'?'message user':'message'} key={i}><small>{m.role==='user'?'YOU':'ROGUE'}</small><p>{m.content}</p></div>)}{busy&&<div className="message"><small>ROGUE</small><p className="typing">Thinking + researching…</p></div>}</div><div className="aiBox"><input value={q} onChange={e=>setQ(e.target.value)} onKeyDown={e=>e.key==='Enter'&&ask()} placeholder="Ask ROGUE…"/><button onClick={()=>ask()}>SEND ↗</button></div></>}
 {tab==="Portfolio"&&<><PageHead title="Portfolio Lab" text="Local paper portfolio with live mark-to-market values. No real orders are sent."/><div className="stats"><Metric l="CASH" v={fmt(paperCash)}/><Metric l="PORTFOLIO" v={fmt(portfolioValue)}/><Metric l="POSITIONS" v={String(Object.values(paperPos).filter(x=>x>0).length)}/><Metric l="MODE" v="PAPER"/></div><div className="cards2"><div className="panel trade"><Title t="PAPER ORDER" s="SIMULATED"/><select value={paperSymbol} onChange={e=>setPaperSymbol(e.target.value)}>{watch.map(s=><option key={s}>{s}</option>)}</select><input type="number" min="1" value={paperQty} onChange={e=>setPaperQty(Number(e.target.value))}/><div className="buttons"><button onClick={buy}>BUY</button><button onClick={sell}>SELL</button></div></div><div className="panel"><Title t="POSITIONS" s="LIVE PRICES"/>{Object.entries(paperPos).filter(([,n])=>n>0).map(([s,n])=><div className="row" key={s}><b>{s}</b><span>{n} shares</span><strong>{fmt(quotes.find(x=>x.symbol===s)?.price)}</strong></div>)}</div></div></>}
 {tab==="Alerts"&&<><PageHead title="Alerts" text="Browser-local price alerts. Keep the terminal open for the most responsive monitoring."/><div className="add alertAdd"><select value={alertSymbol} onChange={e=>setAlertSymbol(e.target.value)}>{watch.map(s=><option key={s}>{s}</option>)}</select><select value={alertDir} onChange={e=>setAlertDir(e.target.value)}><option value="above">Crosses above</option><option value="below">Crosses below</option></select><input value={alertPrice} onChange={e=>setAlertPrice(e.target.value)} placeholder="Price"/><button onClick={()=>{const p=Number(alertPrice);if(!p)return;setAlerts(v=>[...v,{id:globalThis.crypto.randomUUID(),symbol:alertSymbol,dir:alertDir,price:p,fired:false}]);setAlertPrice('')}}>CREATE</button></div><div className="news">{alerts.map(a=><div className="alert" key={a.id}><b>{a.symbol} {a.dir} {fmt(a.price)}</b><span>{a.fired?'TRIGGERED':'ARMED'} · current {fmt(quotes.find(q=>q.symbol===a.symbol)?.price)}</span><button onClick={()=>setAlerts(v=>v.filter(x=>x.id!==a.id))}>REMOVE</button></div>)}</div></>}
 <footer>ROGUE MARKETS · LIVE RESEARCH TERMINAL <span>Not financial advice · data may be delayed, incomplete or unavailable</span></footer></section></main>
}
function Dashboard(p:any){return <><section className="hero"><div className="eyebrow">ROGUE INTELLIGENCE</div><h1>See everything.<br/><em>Ask anything.</em></h1><p>One terminal for live markets, crypto, token research, news, watchlists, paper trading, alerts and AI-assisted research.</p><div className="ask"><span>⌕</span><input value={p.q} onChange={e=>p.setQ(e.target.value)} onKeyDown={e=>e.key==='Enter'&&p.ask()} placeholder="Ask ROGUE: why is NVDA moving? inspect a token…"/><button onClick={()=>p.ask()}>ASK ↗</button></div><div className="chips">{['Analyze my watchlist','Find unusual movers','Explain token liquidity','What changed today?'].map((x:string)=><button onClick={()=>p.ask(x)} key={x}>{x}</button>)}</div></section><div className="stats"><Metric l="WATCHLIST" v={String(p.watch.length)}/><Metric l="MARKET FEED" v={p.quotes.length?'LIVE':'—'}/><Metric l="AI" v={p.health?.ai?'ONLINE':'SETUP'}/><Metric l="$ROGUE" v="PUMP.FUN"/></div><div className="cards2"><QuotePanel quotes={p.quotes} watch={p.watch} setWatch={p.setWatch}/><div className="panel"><Title t="MARKET PULSE" s="LIVE"/>{p.movers.slice(0,7).map((x:any)=><div className="row" key={x.symbol}><b>{x.symbol}</b><span>{fmt(x.price)}</span><em className={num(x.change)>=0?'up':'down'}>{pct(x.change)}</em></div>)}</div></div><div className="panel chartPanel"><div className="chartHead"><Title t={`${p.chartSymbol} CHART`} s="5D · 5M"/><select value={p.chartSymbol} onChange={e=>p.setChartSymbol(e.target.value)}>{p.watch.map((s:string)=><option key={s}>{s}</option>)}</select></div><Spark points={p.chart}/></div><div className="buyBanner"><div><b>ROGUE IS ON PUMP.FUN</b><span>Verify the mint address before purchasing.</span></div><a href={p.buyUrl} target="_blank" rel="noreferrer">OPEN PUMP.FUN ↗</a></div></>}
function Spark({points}:{points:any[]}){if(!points.length)return <div className="noData">Loading chart data…</div>;const vals=points.map(x=>num(x.p));const min=Math.min(...vals),max=Math.max(...vals),w=900,h=220;const path=vals.map((v,i)=>`${i?'L':'M'} ${(i/(vals.length-1))*w} ${h-((v-min)/(max-min||1))*h}`).join(' ');return <svg viewBox={`0 0 ${w} ${h}`} className="spark"><path d={path}/></svg>}
function QuotePanel({quotes,watch,setWatch}:{quotes:Quote[],watch:string[],setWatch:any}){return <div className="panel"><Title t="WATCHLIST" s={`${quotes.length}/${watch.length} LIVE`}/>{quotes.map(q=><div className="row quoteRow" key={q.symbol}><button onClick={()=>setWatch(watch.filter(x=>x!==q.symbol))}>★</button><b>{q.symbol}</b><span>{fmt(q.price)}</span><em className={num(q.change)>=0?'up':'down'}>{pct(q.change)}</em></div>)}</div>}
function List({title,items}:{title:string,items:Quote[]}){return <div className="panel"><Title t={title} s="LIVE"/>{items.map(q=><div className="row" key={q.symbol}><b>{q.symbol}</b><span>{fmt(q.price)}</span><em className={num(q.change)>=0?'up':'down'}>{pct(q.change)}</em></div>)}</div>}
function Title({t,s}:{t:string,s:string}){return <div className="title"><b>{t}</b><span>{s}</span></div>}
function Metric({l,v}:{l:string,v:string}){return <div className="metric"><small>{l}</small><b>{v}</b></div>}
function Signal({t,d}:{t:string,d:string}){return <div className="signal"><i/><div><b>{t}</b><p>{d}</p></div></div>}
function PageHead({title,text}:{title:string,text:string}){return <div className="pageHead"><div className="eyebrow">ROGUE MODULE</div><h1>{title}</h1><p>{text}</p></div>}
